# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Data utworzenia')),
                ('title', models.CharField(max_length=200, verbose_name='Tytu\u0142')),
                ('content', models.TextField(verbose_name='Tre\u015b\u0107')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Imi\u0119')),
                ('last_name', models.CharField(max_length=20, verbose_name='Nazwisko')),
                ('school_class', models.CharField(max_length=2, verbose_name='Klasa')),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Zesp\xf3\u0142',
                'verbose_name_plural': 'Zespo\u0142y',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volley.Team'),
        ),
    ]
